### ISSUE TITLE
JS Error in Chrome - "Cannot read property 'style' of null"

### ISSUE THREAD

**Issue by IsaiahvH** [hansemannn/chrome-mojave-checkbox-extension#3]
Hello,

First of all; thanks for this neat plugin!
I have the issue that on some sites on Chrome (Version 67.0.3396.99), it causes the JS error `content.js:5 Uncaught TypeError: Cannot read property 'style' of null` several times; for example at [Didactigo](https://new.didactigo.com).

How can this be prevented? Is it because the body is called upon, but perhaps it isn't loaded yet?

Kind regards,

Isaiah van Hunen
![image](https://user-images.githubusercontent.com/1858814/42388170-f802b388-8144-11e8-8b1d-f94d142325f7.png)
![image](https://user-images.githubusercontent.com/1858814/42388189-07154b7e-8145-11e8-9398-2f16000cb327.png)

**Comment by hansemannn** [comment]
Hey there, thanks for reporting this! It looks like the body is not available when the extension does it's work. The page may use async client-side rendering which may lead to this result. The call could be guarded and it would resolve the error, but it would also prevent the plugin from working for these sites. I am more of an iOS guy, but I can evaluate it!

**EDIT**: Wait! It looks like the rendering is also re-calling the plugin and actually fixes the zoom after successfully accessing the DOM. Updating the plugin now!

**Comment by hansemannn** [comment]
Should be fixed via https://github.com/hansemannn/chrome-mojave-checkbox-extension/commit/e483af2c2d72820580d1e30732a3c84399415e77 in v1.0.1. The update shoud appear in Chrome soon, otherwise via the [Chrome WebStore](https://chrome.google.com/webstore/detail/mojave-checkbox-fix/ihlgehdlkphgngjfagonbeoepadbdaae). Awaiting your confirmation before closing.

**Comment by IsaiahvH** [comment]
Hi!
All completely on point and the issue is now resolved!

Many thanks (also for the quick reply :)!
