### ISSUE TITLE
use css fix

### ISSUE THREAD

**Issue by aoao** [hansemannn/chrome-mojave-checkbox-extension#4]
only checkbox
```css
input[type="checkbox"] {
	zoom: 1.0000001
}
```

**Comment by hansemannn** [comment]
@aoao Thanks for the suggestion! Unfortunately, there are some more UI elements affected by this, like various kind of system-rendered buttons. Mapping all of them manually seemed a larger overhead than just changing the DOM. If you have performance concerns, let me know!
