### ISSUE TITLE
Not working on w3schools site

### ISSUE THREAD

**Issue by planetf1** [hansemannn/chrome-mojave-checkbox-extension#5]
Fantastic idea & appreciated -- though it does not appear to work on yesterday's macos beta, nor the previous one, with current google chrome beta FOR the page

https://www.w3schools.com/tags/tryit.asp?filename=tryhtml_input_checked

It does work with

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox

Environment:
macos: 10.14 Beta (18A336e)
chrome: 68.0.3440.59

I am using the extension from the chrome store

I'm not sure yet whether it works on most pages or not. Thanks so much for building the extension though.

**Comment by hansemannn** [comment]
Hey there! It looks like it's using an iFrame that forces the zoom-level, but I'd need to investigate it further.

**Comment by PythonicNinja** [comment]
@hansemannn @planetf1 It needs to set it also on iframe body level

![zrzut ekranu 2018-07-19 o 12 50 08](https://user-images.githubusercontent.com/1098417/42938363-549d929a-8b52-11e8-91b3-bc0454692cbc.png)

**Comment by hansemannn** [comment]
Fixed in 1.0.2!

**Comment by PythonicNinja** [comment]
thanks 👍
